version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pewnylink_postgres
    restart: always
    environment:
      POSTGRES_USER: pewnylink_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: pewnylink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: