"""add_user_reports_relationship

Revision ID: 6b0888595e92
Revises: 1b8bfba15ba9
Create Date: 2026-08-12 22:43:33.299291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0888595e92'
down_revision: Union[str, Sequence[str], None] = '1b8bfba15ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
