"""initial_schema

Revision ID: e9857ac148f7
Revises: 
Create Date: 2026-08-10 00:12:17.694165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9857ac148f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Klucz główny użytkownika'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unikalny e-mail (login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Zahasłowane hasło (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Imię i nazwisko lub nazwa firmy'),
    sa.Column('role', sa.Enum('USER', 'VIP_GUEST', 'SUPER_ADMIN', name='userrole', native_enum=False), nullable=False, comment='Rola w systemie'),
    sa.Column('access_until', sa.DateTime(timezone=True), nullable=True, comment='Data wygaśnięcia płatnego dostępu / vouchera (UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data rejestracji konta'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('days_validity', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=False),
    sa.Column('seller_type', sa.String(length=64), nullable=False),
    sa.Column('total_price_with_tco', sa.Float(), nullable=False),
    sa.Column('total_tco_extra', sa.Float(), nullable=False),
    sa.Column('suggested_discount', sa.Float(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
